### ISSUE TITLE
Broken docs links on npmjs.com

### ISSUE THREAD

**Issue by piotr-cz** [PepsRyuu/nollup#103]
Package page on <https://www.npmjs.com/package/nollup> has broken links to documentation on GitHub.

I'm not sure if relative URLs would help: `[Nollup CLI](docs/cli.md)`, but absolute should for sure: `[Nollup CLI](https://github.com/PepsRyuu/nollup/docs/cli.md)`.

Moreover as package.json is missing `homepage` and `repository`  fields, there are no hyperlinks to this repo, this may be fixed by adding:

```json
  "repository": {
    "type": "git",
    "url": "https://github.com/PepsRyuu/nollup.git"
  },
  "homepage": "https://github.com/PepsRyuu/nollup",
````

**Comment by PepsRyuu** [comment]
Want to submit a PR? :)

**Comment by piotr-cz** [comment]
Done. I've created PR which updates package metadata.
However I'm not sure if this will fix links.

**Comment by PepsRyuu** [comment]
It works! https://www.npmjs.com/package/nollup 

Thanks for the fix! :)

**Comment by piotr-cz** [comment]
Great, homepage field fixed that!
BTW: your other packages are missing these fields too
