### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by tomByrer** [PepsRyuu/nollup#108]
I'm not sure if I need to install globally , or ...?

I just went into `\nollup-master\examples\example-preact\` & `yarn` & got an error when I `yarn start`:
`Error: Cannot find module 'express'`

**Comment by PepsRyuu** [comment]
Install Nollup repository first, then install the examples and start them. The examples reference Nollup relatively. :)

I'll update the main example README to clarify that.

**Comment by PepsRyuu** [comment]
Added a note to clarify this: https://github.com/PepsRyuu/nollup/tree/master/examples

**Comment by tomByrer** [comment]
TY

I'll have to check it out in a week or so.
