### ISSUE TITLE
Nullish coalescing support

### ISSUE THREAD

**Issue by Alexsey** [PepsRyuu/nollup#114]
It would be nice to have it. Rollup is already supporting it https://github.com/rollup/rollup/pull/3548

**Comment by PepsRyuu** [comment]
Is it specifically the Acorn parser that's failing in the error logs? I assume just updating that will do the trick.

**Comment by PepsRyuu** [comment]
Installing a fresh project seems to work for me, can you confirm the version of Acorn that's installed in the ```node_modules``` directory? Can you try deleting the directory and ```package-lock.json``` and re-run ```npm install```?

**Comment by Alexsey** [comment]
I've got 7.1.0. Then I've updated it to 7.3.1 and it worked! So yes, just bumping acorn works. Can I create a PR with the minimal version bump, so non-fresh installs of nollup can also got it work out of the box?

**Comment by PepsRyuu** [comment]
Go for it! :)

**Comment by PepsRyuu** [comment]
Fix published in ```0.13.0```. :)
