### ISSUE TITLE
Crashes when using @rollup/plugin-virtual in Bundle Input mode

### ISSUE THREAD

**Issue by piotr-cz** [PepsRyuu/nollup#123]
Nollup crashes when using [@rollup/plugin-virtual](https://github.com/rollup/plugins/tree/master/packages/virtual) in [Bundle Input](https://github.com/rollup/plugins/tree/master/packages/virtual#using-the-plugin-for-bundle-input) mode, as the it expects entry input to be physical path on disk.

Rollup config for reproducting error

```js
import rollupPluginVirtual from '@rollup/plugin-virtual'

const configString = JSON.stringify({ foo: 'bar' }}

export default {
  input: 'build-env',
  output: {
    file: 'build/build-env.js',
    format: 'iife',
    name: 'APP_ENV',
  },
  plugins: [
    rollupPluginVirtual({ 'build-env': `export default ${configString}` }),
  ],
}
```

CLI Output:
```
Error: ENOENT: no such file or directory, open 'xxx\build-env'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.load (xxx\node_modules\nollup\lib\impl\PluginLifecycle.js:171:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async compileModule (xxx\node_modules\nollup\lib\impl\NollupCompiler.js:56:22)
    at async compileInputTarget (xxx\node_modules\nollup\lib\impl\NollupCompiler.js:137:5)
    at async Object.compile (xxx\client\node_modules\nollup\lib\impl\NollupCompiler.js:208:31)
    at async generateImpl (xxx\node_modules\nollup\lib\index.js:13:21)
```

I have no idea how to handle this, but maybe there could be a section in the Nollup docs about [Official Rollup](https://github.com/rollup/plugins) plugins that are not compatible by design.

**Comment by PepsRyuu** [comment]
Thanks for the repro! I don't see why this plugin can't work. Just need to get resolveId to trigger for input which is possible. Currently on holidays so won't be able to fully address this for a few days still, so bear with me! :) 

I also would have no objections to having a section about incompatible plugins, but I think most incompatible ones at the moment can be fixed by either Nollup or the plugin themselves (some plugins for example use ```fs``` instead of ```emitFile```).

**Comment by piotr-cz** [comment]
Take your time on holidays, thank you for fantastic work you've done!

**Comment by PepsRyuu** [comment]
Should be resolved with this change: https://github.com/PepsRyuu/nollup/pull/124

**Comment by piotr-cz** [comment]
Yes, #124 fixes the issue, thanks!

I found another problem related to the repro case: IIFE variable (`APP_ENV`) is not created but that's another issue.
