### ISSUE TITLE
Suppert for TLS and CORS-Headers

### ISSUE THREAD

**Issue by morbidick** [PepsRyuu/nollup#127]
Hi,
thank you for your awesome work. I am in a Team developing an online shop using a microfrontend approach, so we are pulling in different modules from different servers. Currently we are using webpack-dev-server but would very much like to switch to rollup/nollup.
For that to work we would need support for TLS and the possibility to add CORS-Headers (allow-origin: *) in nollup. Is that something you would be interested in a PR or should we wrap the nolllup-middleware  with our own express server?

**Comment by PepsRyuu** [comment]
Support for running in a HTTPS server sounds like it would be a good addition!

For CORS, there's currently ```before``` and ```after``` hooks where you can inject custom middleware into. Would that address that use case?

**Comment by morbidick** [comment]
The hook sounds interesting, I'll look into it. For HTTPS I will try to do a PR in the next few days :)

**Comment by hanswilw** [comment]
Example with cors() https://github.com/PepsRyuu/nollup/issues/120#issuecomment-667726744 :)

**Comment by PepsRyuu** [comment]
```headers``` option will be released in next version ```0.13.5```
