### ISSUE TITLE
How to debug nollup?

### ISSUE THREAD

**Issue by Filyus** [PepsRyuu/nollup#135]
How to debug nollup with VS Code? I have never debugged scripts inside of node_modules path. Is there a ready-made launch.json for it?

**Comment by PepsRyuu** [comment]
I'm not familiar with debugging in VSCode, but I usually just use the following from the terminal:

```
node --inspect-brk node_modules/nollup/lib/cli.js -c --environment NODE_ENV:development
```
And then use the Chrome NodeJS debugger to walk through the code.

Otherwise I just modify the files directly in ```node_modules``` and start sticking in console logs and debugger statements.

**Comment by Filyus** [comment]
Thanks! It helped.
