### ISSUE TITLE
Get changed module information

### ISSUE THREAD

**Issue by dazinator** [PepsRyuu/nollup#14]
Hello,

I have my own in process dev server running (in asp.net core) website, it calls out to rollup to process files, and has a rudimentary browser reload based on signalr. I am now looking at adding HMR capability and have been looking at https://github.com/alexisvincent/systemjs-hmr

I have noticed that when calling rollup, it produces a bundle file, but I have no access to information about the "module names" that changed since last time. It seems if I wanted to trigger a reload of a hot module in the browser it would be helpful to atleast establish the module name that changed..

So this lead me to `nollup`. Could `nollup` help me here? I.e if I included a nollup plugin in the rollup build, could I collect information about module id's that have been changed? I would need to collect that information, so that my server could send that information to the browser to then trigger the reload of those modules in the browser.

I am pretty new to all this so I am very much just figuring all this out as I go ;-)

**Comment by PepsRyuu** [comment]
Hi @dazinator!

No problem at all, thanks for the interest!

When using nollup, as part of the response when calling ```generate()```, it will provide changed modules with their ids. You can see an example of this here in the dev server: https://github.com/PepsRyuu/nollup/blob/master/lib/dev-middleware.js#L169

The dev server included in nollup uses these changes to provide HMR for Rollup projects. I recommend taking a look at the examples included in this repository: https://github.com/PepsRyuu/nollup/tree/master/examples

If there's anything more specific you need to know, feel free to ask! :) 

Hope this helps!

**Comment by PepsRyuu** [comment]
Not quite. Nollup isn't a plugin, it's a compiler. It's interchangeable with Rollup. 

The easiest thing to do for existing Rollup projects is to use the Express JS middleware if you can. It takes care of calling nollup and embeds a HMR runtime.

**Comment by dazinator** [comment]
> Nollup isn't a plugin, it's a compiler. It's interchangeable with Rollup

Oh right I see - apologies my mistake. This explains why I couldn't see mention of such a plugin when browsing the sample code ;-)

> The easiest thing to do for existing Rollup projects is to use the Express JS middleware if you can

Ok thanks for the suggestion. I am keen to keep my existing asp.net core server, and I don't want to have to start a seperate server and proxy anything. I am very much approaching this from the perspective of building HMR into the asp.net core middleware pipeline for use with asp.net core website projects..

To be honest, I am now thinking that to use HMR with AMD modules and systemJS, I perhaps wouldn't want to bundle them at all. For example, I am thinking of just not invoking rollup at all when HMR is enabled, and then letting systemJS resolve them. I am pretty sure I can configure SystemJS to resolve module id's from a single bundle file (when rollup is enabled) or from seperate fiiles (when rollup isn't enabled) I just need to find a way of preserving AMD module Id's (and define() calls) when rollup builds the AMD modules into a single bundle file. Anyway - thanks for your help, I will close this :-)
