### ISSUE TITLE
Yarn 2 complains

### ISSUE THREAD

**Issue by derolf** [PepsRyuu/nollup#144]
Just upgraded to yarn 2 and I get the following error:

```
 YN0001: │ HTTPError: source-map-fast@npm:0.7.3: Response code 404 (Not Found)
```

It looks like yarn 2 doesn't like the alias in nollup/package.json:

```
"source-map-fast": "npm:source-map@0.7.3"
```

**Comment by PepsRyuu** [comment]
Hi @derolf 

I'm not a ```yarn``` user so I don't really know the details of it, but it sounds like this is a Yarn bug, as the syntax used in ```package.json``` is supported by ```npm```. I would report the issue there as it seems like something they would need to add support for if they're missing it.

**Comment by derolf** [comment]
I cleared `node_modules` and did an installation from scratch. Now seems to work... Sorry :-(
