### ISSUE TITLE
Cross-Imports might yield `undefined` function

### ISSUE THREAD

**Issue by derolf** [PepsRyuu/nollup#148]
I am using openapi-generator and it generates a `models/index.ts` of the form:

```TypeScript
export * from './A'; // exports func_from_A
export * from './B'; // exports func_from_B
export * from './C';
```

Now, these files A/B/C import stuff from each other via "./", like:

```TypeScript
import { func_from_B, func_from_A } from './';

export function foo() {
  func_from_A();
}
```

Calling `foo` now results into `TypeError: undefined is not a function` when it tries to call `func_from_A`. So, for some reason, `func_from_A` is undefined when calling it from `foo`.

Works when bundled via `rollup`.

**Comment by PepsRyuu** [comment]
I can't seem to reproduce this following the instructions. Can you create a minimal reproducible example?

For making a quick reproducible example: ```npx create-nollup-app --name repro --template barebones``` :)

**Comment by derolf** [comment]
Here you go: https://github.com/derolf/nollup-bug

nollup: `Failed TypeError: models_1.b_foo is not a function. (In 'models_1.b_foo()', 'models_1.b_foo' is undefined)`
rollup: `works`

Note that the directory structure within `src/bug` is commonly produced by the openapi-generator...

**Comment by derolf** [comment]
Here's a random example found at GitHub that is likely to have the same problem: https://github.com/Splitit/Splitit.SDKs/tree/master/TypeScript/dist

**Comment by PepsRyuu** [comment]
Ah it's a circular dependency issue. This is probably going to be very complicated to fix. Will have to have a deeper look into it and see if it's feasible to resolve.

**Comment by PepsRyuu** [comment]
Small update: This seems to be related to how TypeScript is transpiling code, and it seems to conflict with Nollup's implementation. I suspect it's related to the "Object.defineProperty" line.

Switching to ```@rollup/plugin-typescript``` and removing the compiled JS files from the ```src``` directory makes the application work fine.

```
import node_resolve from "rollup-plugin-node-resolve";
import static_files from "rollup-plugin-static-files";
import { terser } from "rollup-plugin-terser";
import commonjs from "@rollup/plugin-commonjs";
import typescript from '@rollup/plugin-typescript';

let config = {
  input: "./src/main.ts",
  output: {
    dir: "dist",
    format: "esm",
    entryFileNames: "[name].[hash].js",
    assetFileNames: "[name].[hash][extname]",
  },
  plugins: [node_resolve(), typescript(),  commonjs()],
};

export default config;
```

**Comment by PepsRyuu** [comment]
Seems to be a combination of CommonJS proxy and circular dependency that's breaking here. Not sure this is possible to fix without implementing live bindings.
