### ISSUE TITLE
Problems with styled components

### ISSUE THREAD

**Issue by felipeferreiraads** [PepsRyuu/nollup#150]
Hi,

I'm trying to plug my app with Nollup Dev Middleware, but i'm getting this:

`preferring built-in module 'stream' over local alternative at 'stream', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
ParseError: /node_modules/styled-components/dist/stream.js
Error: ENOENT: no such file or directory, open '/usr/src/lms-web/node_modules/styled-components/dist/stream.js'
`
After this, I tried to run with `nodeResolve({ preferBuiltins: false })` but still getting error.

My config: 
`
const config = {
  input: path.join(__dirname, 'src', 'web', 'private', 'student'),
  output: {
    dir: 'src/web/public/javascript/dist',
    format: 'esm',
    entryFileNames: '[name].[hash].js',
    assetFileNames: '[name].[hash][extname]',
  },
  plugins: [
    multi(),
    hotcss({
      hot: process.env.NODE_ENV === 'development',
      filename: 'styles.css',
    }),
    babel({
      exclude: 'node_modules/**',
    }),
    nodeResolve({ preferBuiltins: false }),
    commonjs({
      define: {
        'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
      },
    }),
    process.env.NODE_ENV === 'development' && refresh(),
  ],
};
`

Tks for the attention.

**Comment by PepsRyuu** [comment]
Hi @felipeferreiraads! Can you provide a minimal reproducible example of the issue?

**Comment by PepsRyuu** [comment]
Closing as no reproducible example has been provided, so assuming this was not an issue with Nollup.
