### ISSUE TITLE
Can't import @reach/router

### ISSUE THREAD

**Issue by vndre** [PepsRyuu/nollup#168]
**current output:**
```TypeError: createContext is not a function```

**Steps to reproduce:**
1. clone react-refresh example
2. add **@reach/router** as dependency
3. add `<Router>` wrapper to App

Sadly I don't have the time to dig into the issue but maybe it has to do with the plugin `rollup-plugin-commonjs-alternate`?

@reach/router has a dependency `create-react-context` which is imported as: `import createContext from 'create-react-context`... Debugging a little shows that `createContext` is undefined after the imports already occured, any clue what could be happening? thanks for the help.

**Comment by PepsRyuu** [comment]
Thanks for the report, it is indeed ```rollup-plugin-commonjs-alternate```.

Should be an easy fix. Will have a look into it.

**Comment by PepsRyuu** [comment]
Update ```rollup-plugin-commonjs-alternate``` to ```0.7.2``` 😊

**Comment by vndre** [comment]
wow man, that was fast!

**Comment by vndre** [comment]
I can confirm that `rollup-plugin-commonjs-alternate` version `0.7.2` fixes this issue.

**Comment by PepsRyuu** [comment]
Haha, no problem at all! 😂

I don't think it's possible to get me a drink, but I appreciate the thought! 😋
