### ISSUE TITLE
Feature request: Add config option to bind server to any IP

### ISSUE THREAD

**Issue by rraihansaputra** [PepsRyuu/nollup#170]
I'm currently developing a mobile focused app, and would like to access the nollup app on my phone through LAN. 

The change on express is adding the IP address as an argument on the `.listen` function, but it may involve changes to the HMR to refer to the LAN IP instead of just the localhost.

The binding to `0.0.0.0` is automatically the default on `vue-cli` `yarn serve` so the served project can be accessed instantly on the network without any configuration.

**Comment by PepsRyuu** [comment]
Isn't this potentially opening up a security hole if it's on by default?

I assume having it similar to Webpack would suffice? https://webpack.js.org/configuration/dev-server/#devserverhost I've no objections to implementing it this way and making it an opt-in.

**Comment by rraihansaputra** [comment]
I agree, implementing it similar to Webpack would suffice. I mentioned vue-cli as an example because that's the one I have experience with. The security concern is valid and I do prefer having it opt-in. 👍

**Comment by PepsRyuu** [comment]
https://github.com/PepsRyuu/nollup/pull/171/files I'm not sure if this is correct because I can't seem to replicate it. If you can give it a try, let me know if it works for you.

**Comment by rraihansaputra** [comment]
@PepsRyuu happy to report that it works for me by just changing the `host: "0.0.0.0"` on `.nolluprc.js`. I left a comment on the PR to display the host IP on the CLI log. Thank you 👍

**Comment by rraihansaputra** [comment]
Closing this as #171 is merged. Once again Thank you @PepsRyuu!
