### ISSUE TITLE
dev-middleware example

### ISSUE THREAD

**Issue by iWun** [PepsRyuu/nollup#174]
I'm new to nollup.
I find a doc about [dev-middleware](https://github.com/PepsRyuu/nollup/blob/master/docs/dev-middleware.md), where can i find a dev-middleware  example?
thanks.

**Comment by PepsRyuu** [comment]
The code snippet there is pretty much the minimal example, as the rest of the surrounding code is just typical Express code. I recommend checking out the ```dev-server``` implementation with is fairly minimal and uses the ```dev-middleware``` internally: https://github.com/PepsRyuu/nollup/blob/master/lib/dev-server.js

Hope this helps!

**Comment by iWun** [comment]
> The code snippet there is pretty much the minimal example, as the rest of the surrounding code is just typical Express code. I recommend checking out the `dev-server` implementation with is fairly minimal and uses the `dev-middleware` internally: https://github.com/PepsRyuu/nollup/blob/master/lib/dev-server.js
> 
> Hope this helps!

Thanks, I will study it carefully
