### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by sooxt98** [PepsRyuu/nollup#176]
I added nollup to default svelte template, and i get this issue; The output from `nollup -c` seems normal

```
> svelte-app@1.0.0 dev /Users/sheldon/dev/Futurize/WBLS
> nollup -c

[Nollup] Listening on http://localhost:8080
LiveReload enabled
[Nollup] Compiled in 39515ms.
```

**Comment by PepsRyuu** [comment]
That usually means the ```index.html``` file is missing. Do you have a reproducible example?

**Comment by sooxt98** [comment]
@PepsRyuu just use the svelte default starter template, my public have index.html it just not found

**Comment by sooxt98** [comment]
i added this, and it works fine not; but the page wont get reload when i update the code; 
![image](https://user-images.githubusercontent.com/13378059/105622062-f3732d00-5e48-11eb-8ac6-a6dd0a3901f1.png)

**Comment by PepsRyuu** [comment]
Great! Might be worth mentioning the issue in the starter repository. 🙂
