### ISSUE TITLE
Trouble with HMR & NollupDevMiddleware

### ISSUE THREAD

**Issue by CreaturesInUnitards** [PepsRyuu/nollup#177]
I have a substantial Express setup which mandates the use of `dev-middleware`. I have everything running, I'm seeing the expected `[Nollup] Compiled in 3ms` console logs with every change to the codebase, but HMR is failing. (Actually I'm just trying to get a full refresh.)

I included the refresh boilerplate in my `main.js`, which was working fine before I brought my own server into the mix:
```js
if (module) {
	module.hot.accept(() => {
		window.location.reload()
	})
}
```

Here's what shows up in my browser console:
```
WebSocket connection to 'ws://localhost:9001/__hmr' failed: Unexpected response code: 404
```

I'm using the standard `rollup.config.js` provided by `create-nollup-app`, converted to CommonJS so it can be `require`d in my server config file:
```js
...
const NollupDevMiddleware = require('nollup/lib/dev-middleware')
const rollupConfig = require('../rollup.config.js')

app.use(NollupDevMiddleware(app, rollupConfig, {
	hot: true,
	contentBase: './public',
	port: 9001
}))
...
```

Any help would be greatly appreaciated. Thanks.

**Comment by PepsRyuu** [comment]
Hmmm, based on what you've shared, I'm not seeing any reason why it should be failing. I can only speculate that there's something conflicting with the Express setup you're using, perhaps a middleware before Nollup that's responding and not calling ```next()``` correctly. 

Are you able to share any reproducible example?

**Comment by CreaturesInUnitards** [comment]
Here's my test server in its entirety:

```js
const app = require('express')()
const bodyParser = require('body-parser')
const http = require('http')
const NollupDevMiddleware = require('nollup/lib/dev-middleware')
const rollupConfig = require('../rollup.config.js')

app.use(NollupDevMiddleware(app, rollupConfig, {
	hot: true,
	contentBase: './public',
	port: 9001
}))

app.use(bodyParser.json({ limit: '50mb' }))
app.use(bodyParser.urlencoded({
	limit: '50mb',
	extended: true,
	parameterLimit: 50000
}))

const port = 9001
app.set('port', port)

/****************  ROUTES  ******************/
app.get('/', (req, res) => {
	res.sendFile(`${__dirname}/public/index.html`)
})
/** ************************************** **/

const server = http.createServer(app)
server.listen(port, () => {
	console.log(`Server listening on port ${port}`)
})
```

**Comment by PepsRyuu** [comment]
Ah the issue there is that you're running a server outside of Express. The middleware uses ```express-ws``` which needs a reference to the server instance. This is normally taken care of by Express. Replacing the last section with ```app.listen(port)``` will make it work just fine.

Another option is to pass ```server``` as the fourth argument into the middleware. I just noticed this is undocumented, so I'll keep this issue open until I fix that:

```
app.use(NollupDevMiddleware(app, rollupConfig, {
	hot: true,
	contentBase: './public',
	port: 9001
}, server))
```

Let me know if that sorts you out! :)

**Comment by CreaturesInUnitards** [comment]
Outstanding! Yes that's it. Thanks so much.

**Comment by PepsRyuu** [comment]
Doc will be updated in refactored code base to be released soon.
