### ISSUE TITLE
Is it possible to use "proxy" option from cli or using the cli way?

### ISSUE THREAD

**Issue by frederikhors** [PepsRyuu/nollup#180]
I didn't understand from the documentation if I can use the proxy option with the cli.

Specifically I'm using this project: https://github.com/rixo/svelte-template-hot.

Is it possible?

**Comment by PepsRyuu** [comment]
Not from the CLI no. You can use a ```.nolluprc.js``` file. https://github.com/PepsRyuu/nollup/blob/master/docs/nolluprc.md

**Comment by PepsRyuu** [comment]
So for the example in the linked issue:

**.nolluprc.js**
```
module.exports = {
    proxy: {
        '/api/todos': 'http://myserver:3000'
    }
}
```

**Comment by frederikhors** [comment]
I''m using it. It doesn't work. Hence the question.

**Comment by frederikhors** [comment]
It does work. Sorry.

**Comment by frederikhors** [comment]
What doesn't work now is this:

With this config:

```js
module.exports = {
    proxy: {
        '/api/todos': 'http://myserver:3000'
    }
}
```

this URL:

`http://localhost:5000/api/todos?variable="Hello"`

gets proxied to:

`http://myserver:3000/api/todos/?variable="Hello"`

Note the `/` after `todos`.

Why?

Am I wrong somewhere?

**Comment by frederikhors** [comment]
I think the last point deserves a new issue.
