### ISSUE TITLE
Proxy routes glob?

### ISSUE THREAD

**Issue by frederikhors** [PepsRyuu/nollup#182]
It would be awesome to have proxy handle these:

```js
module.exports = {
  proxy: {
    '/api/todos/*': 'http://myserver:3000',
    '/custom/*': 'http://myserver:3000'
  }
}
```

Is it possible?

**Comment by PepsRyuu** [comment]
Unless I'm misunderstanding this, this isn't necessary. A proxy route for ```/api``` will work for everything that begins with ```/api```.
