### ISSUE TITLE
Plugin error reporting is raw JSON instead of pretty

### ISSUE THREAD

**Issue by mizzao** [PepsRyuu/nollup#183]
When I run Rollup, errors show up like this:

![image](https://user-images.githubusercontent.com/2080084/108763803-cb4a1d00-751f-11eb-8cc6-32f50b46a888.png)

But with nollup they show up like this: 

![image](https://user-images.githubusercontent.com/2080084/108763855-dbfa9300-751f-11eb-952d-7933e7ea0f8b.png)

All errors appear to have this difference. Is there a simple way to use the nice formatting implied by the JSON instead of just outputting it raw? Perhaps I have misconfigured something, but if not happy to help improve the functionality here.

**Comment by PepsRyuu** [comment]
It's an error object I haven't taken into account. I can do something about that reasonably quickly. I'll get back to you on this. :)

**Comment by mizzao** [comment]
Thanks, happy to help you test the implementation!

**Comment by PepsRyuu** [comment]
https://github.com/PepsRyuu/nollup/pull/185/files Seems to do the trick for TypeScript.

**Comment by PepsRyuu** [comment]
Released this initial version in ```0.15.3```

**Comment by mizzao** [comment]
Thanks! I will give it a try.

**Comment by mizzao** [comment]
Works great! This is what rollup vs nollup looks like now. The slight difference doesn't matter to me, but just posting in case you cared:

Rollup:
![image](https://user-images.githubusercontent.com/2080084/109721974-109ec800-7b7a-11eb-9462-cb346ab41577.png)

Nollup:
![image](https://user-images.githubusercontent.com/2080084/109722015-1ac0c680-7b7a-11eb-9a1f-0888a95f8702.png)

**Comment by PepsRyuu** [comment]
I'm not too worried about it. Rollup's error reporting is fairly complicated, and its CLI is even doing stuff like overriding ```console.warn``` which I definitely don't want to do and can't do because of Nollup's middleware API. So there's going to be inconsistencies here no matter what, but an inconsistency here as far as I know is not very important. 🙂
