### ISSUE TITLE
Feature Root path

### ISSUE THREAD

**Issue by shiftmeplease** [PepsRyuu/nollup#193]
Hello, i was trying to use nollup for public path **app/build** and got some errors with serving.
It's working fine if public path not contain any subfolders smth like **build**
In case of "app/build" i have to go [http://localhost:5000/app/build/index.js](url) for example.
Would be great to add root path option, that will make possible to handle such cases

**Comment by shiftmeplease** [comment]
maybe make **public path** only for express request path resolving, but **root path** for local folder

**Comment by PepsRyuu** [comment]
Public path isn't meant to contain any compiled files, it's only a path to indicate where to file additional assets (index, images, fonts, etc). If you want to change the path of the output, you should change the ```entryFileNames``` option in the ```output``` section.

Can you describe the folder structure you have, and ideally what the folder structure will look like after compilation when serving on a normal web server?

**Comment by shiftmeplease** [comment]
thank you, figured out that my config should be
```
module.exports = { 
  ...
  contentBase: 'app/assets',
  publicPath: 'build', 
  ...
}

```
instead of 
```
module.exports = {
  ...
  contentBase: 'app/assets',
  publicPath: 'app/build',
  ...
}
```
