### ISSUE TITLE
where is plugin svelte error detail?

### ISSUE THREAD

**Issue by sup-ham** [PepsRyuu/nollup#195]
![image](https://user-images.githubusercontent.com/3823496/116555214-51228400-a926-11eb-9d28-965bcca2ed4e.png)

this red marked detail shown when using only rollup but not nollup

**Comment by PepsRyuu** [comment]
Do you have a reproducible example handy?

**Comment by sup-ham** [comment]
Yes, you can try use https://github.com/roxiness/routify-starter
make some error at  `src/pages/index.svelte`, as seen in image
![Uploading image.png…]()

run  `npm run nollup` and `npm run rollup` and see difference

**Comment by sup-ham** [comment]
![image](https://user-images.githubusercontent.com/3823496/116646969-a486e780-a9a3-11eb-9770-9a6b38203c37.png)

**Comment by PepsRyuu** [comment]
Thanks for the repro, having a look into it. Should be straightforward to fix. Nollup does pretty format errors, but only when they're using the ```error()``` plugin context function. Looks like this particular plugin is just throwing instances of ```Error``` with modified properties which isn't taken into account at the moment. Will have something published for it soon.

**Comment by sup-ham** [comment]
error detail was showing now. thank you very much.
