### ISSUE TITLE
React/Vue SSR examples

### ISSUE THREAD

**Issue by talentlessguy** [PepsRyuu/nollup#199]
Would be cool to have examples of using Nollup API to bundle React/Vue on top of SSR.

**Comment by PepsRyuu** [comment]
For SSR, I never looked into it before. I'm guessing it's perfectly possible to do with the current plugins available. Is there some sort of difficulty you're having in particular getting SSR to work with Nollup + React?

Vue I had a look into a while back from a HMR perspective, but a new plugin which supports HMR would have to be created. I never used Vue, so I have really no clue how that works at all. If there's any information anyone has for this, would be much appreciated.

**Comment by talentlessguy** [comment]
@PepsRyuu well atm I'm trying to setup a custom fullstack server for Hyperapp and having no examples for SSR makes it a bit more difficult...

atm I have this:

```js
import { App } from '@tinyhttp/app'
import { logger } from '@tinyhttp/logger'
import serve from 'serve-static'
import Nollup from 'nollup/lib/dev-middleware.js'
import { getCountries } from './functions/countries.js'
import { render } from './src/util/server/renderPage.js'

export const createApp = async () => {
  const app = new App()

  const isProd = process.env.NODE_ENV === 'production'

  // API functions
  app.get('/api/countries', getCountries)

  if (isProd) {
    const routes = ['/', '/countries', '/about']

    // Prerender each page in production
    routes.forEach((route) => app.get(route, (_, res) => res.send(render(route))))

    return app.use(serve('dist'))
  } else {
    app.use(
      Nollup(
        app,
        {
          input: 'src/app.js',
          output: {
            dir: 'dist',
            format: 'esm',
            entryFileNames: '[name].[hash].js',
            assetFileNames: '[name].[hash][extname]'
          }
        },
        {
          hot: true,
          contentBase: './public'
        }
      )
    )

    app.use(logger())

    return app
  }
}
```

and this doesn't seem to work:

```
 pnpm dev

> hyperapp-ssr@1.0.0 dev /home/v1rtl/Coding/hyperapp-ssr
> node server.js

ParseError: /src/hyperapp.js
Error: ENOENT: no such file or directory, open '/home/v1rtl/Coding/hyperapp-ssr/src/hyperapp.js'
    at compileModule (/home/v1rtl/Coding/hyperapp-ssr/node_modules/.pnpm/nollup@0.16.3/node_modules/nollup/lib/impl/NollupCompiler.js:200:19)
    at async compileInputTarget (/home/v1rtl/Coding/hyperapp-ssr/node_modules/.pnpm/nollup@0.16.3/node_modules/nollup/lib/impl/NollupCompiler.js:231:5)
    at async Object.compile (/home/v1rtl/Coding/hyperapp-ssr/node_modules/.pnpm/nollup@0.16.3/node_modules/nollup/lib/impl/NollupCompiler.js:302:31)
    at async generateImpl (/home/v1rtl/Coding/hyperapp-ssr/node_modules/.pnpm/nollup@0.16.3/node_modules/nollup/lib/index.js:14:21)
```

it produces such error on each imported module... probably I am doing something wrong

**Comment by PepsRyuu** [comment]
That error is happening because it doesn't know how to resolve ```import { app } from 'hyperapp';```. There's no plugins being passed in the Rollup config to help resolve this (ie. ```@rollup/plugin-node-resolve```.

**Comment by PepsRyuu** [comment]
It's normal for no ```dist``` directory to get created. All of the files exist in memory. ```dist``` only applies for production builds. Does the content in your ```public``` directory get served on the expected port? Does that load and give a 404 for the JavaScript entry file it's trying to load?

**Comment by PepsRyuu** [comment]
If you remove Nollup, and just use the ```serve()``` middleware? 

Also based on your config, you should try ```curl localhost:3000/app.[hash].js```. :)

**Comment by talentlessguy** [comment]
@PepsRyuu

removing Nollup makes it return 404. So the issue comes from middleware probably...

regarding 2nd thing, it still hangs (w/ Nollup):

```sh
➜ curl 'localhost:3000/app.\[hash\].js'
# nothing happening
```

**Comment by PepsRyuu** [comment]
If Nollup says it compiled in ther terminal, it should be available. Hard to tell what's going on though from the setup though if there's other things affecting the server. Let me know when the public folder is being served correctly and we can try figure out what's going on from there!

**Comment by talentlessguy** [comment]
@PepsRyuu public folder is served just fine (without Nollup middleware):

```
➜ curl localhost:3000
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HMR Test</title>
    <link rel="stylesheet" href="/styles.[hash].css" type="text/css" />
  </head>
  <body>
    <div id="app"></div>
    <script async src="/app.[hash].js"></script>
  </body>
</html>
```

**Comment by PepsRyuu** [comment]
What's the full server file looking like, and the terminal output? Does requesting the js file say anything in particular?

**Comment by talentlessguy** [comment]
@PepsRyuu one second I better push my code and will send a branch so you can inspect it yourself :)

repro here: https://github.com/talentlessguy/hyperapp-fullstack-starter/tree/nollup

**Comment by PepsRyuu** [comment]
Thanks for the update. It seems to be some sort of incompatibility with ```@tinyhttp/app```. The ```dev-middleware``` uses ```express-ws``` to create a WebSocket URL for the browser to connect for HMR updates. If I go into Nollup inside ```node_modules``` and comment the ```express-ws``` stuff, it works just fine. I have no idea why it's causing the weird lockup though. I confirmed this is the case by switching out ```tinyhttp``` in your code for ```express``` and it also works just fine.

Might be an issue to report on the ```tinyhttp``` repository, as one of their goals is to have full Express middleware support according to their website.

**Comment by PepsRyuu** [comment]
Reproduction for reference: 

```
import { App } from '@tinyhttp/app';
import expressWs from 'express-ws';
import serve from 'serve-static';

let app = new App();

if (process.argv.indexOf('--bug') > -1) {
    expressWs(app);
}

app.use(serve('./'));

app.listen(8081);

```

**Comment by talentlessguy** [comment]
@PepsRyuu oh sorry for catching too much attention then :(

if it's not a nollup bug then the issue can be closed I suppose

and I need to figure out why it bugs with tinyhttp...
