### ISSUE TITLE
Replace express-ws with something newer?

### ISSUE THREAD

**Issue by talentlessguy** [PepsRyuu/nollup#200]
Hi,

sorry for writing here again, this is mroe like a suggestion rather than a question or bug report.

so, nollup uses [express-ws](https://github.com/HenningM/express-ws). that library is ancient as hell (hasn't been updated for 3 years) and is full of unsolved issues.

see this thread: https://github.com/HenningM/express-ws/issues/135

would it be better to replace express-ws with something newer?

**Comment by talentlessguy** [comment]
@PepsRyuu I'm currently working on a library similar to express-ws... expect a PR soon :D

(fyi this issue was created in case someone will suggest anything better than express-ws)

**Comment by talentlessguy** [comment]
I propose [tinyws](https://github.com/talentlessguy/tinyws) as a replacement.

It's much smaller than express-ws, easier to use and comes with types out of the box (also doesn't depend on any framework but not that important here).

```js
import express from 'express'

import { tinyws } from '../src/index'

const app = express()

app.use('/', tinyws())

app.use('/hmr', async (req, res) => {
  if (req.ws) {
    const ws = await req.ws()

    return ws.send('hello there')
  } else {
    res.send('Hello from HTTP!')
  }
})

app.listen(3000)
```

**Comment by PepsRyuu** [comment]
Removed ```express-ws``` in ```0.18.0``` for plain ```ws```.

**Comment by talentlessguy** [comment]
@PepsRyuu amazing, thanks :D
