### ISSUE TITLE
Debugging in VS Code?

### ISSUE THREAD

**Issue by zgoda** [PepsRyuu/nollup#201]
A question: how do I set up VS Code launch configuration so internal debugger works with nollup based project?

My current config results in unbound breakpoints:

```json
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}/src"
        }
```

For reference, that's my Nollup rc file:

```js
module.exports = {
  contentBase: 'public',
  port: 8080,
  hot: true
};
```

and Rollup bundling config:

```js
{
  input: './src/main.js',
  output: {
    dir: 'build',
    format: 'esm',
    entryFileNames: '[name].[hash].js',
    assetFileNames: '[name].[hash][extname]',
    sourceMap: true,
  },
},
```

**Comment by PepsRyuu** [comment]
I don't use this feature, and in my first time using it, it seems to work fine. What if you remove ```src``` from the webRoot?

**Comment by zgoda** [comment]
Breakpoint is still unbound.

![Zrzut ekranu z 2021-05-23 21-43-13](https://user-images.githubusercontent.com/141999/119274380-ece69d80-bc0f-11eb-9c7a-e2d99e64c8f4.png)

The same VSC launch configuration works for webpack projects with that kind of code layout.

**Comment by PepsRyuu** [comment]
Can you provide a reproducible example?

**Comment by zgoda** [comment]
Minimal repro: https://github.com/zgoda/nollup-vsc-debug-cfg

This is basically Preact template with some minimal code to be able to set breakpoints, eg on line 10 in `src/App.js`. https://github.com/zgoda/nollup-vsc-debug-cfg/blob/master/src/App.js#L10

**Comment by PepsRyuu** [comment]
![image](https://user-images.githubusercontent.com/6637882/119321017-1a653280-bc74-11eb-9720-fe3258384bb1.png)

Works fine for me. I've no idea what could be causing it to not work on your setup.

**Comment by PepsRyuu** [comment]
Oh wait, hang on, do you mean being able to set a breakpoint in the actual source code and have it bound there rather than in the loaded scripts section?

**Comment by PepsRyuu** [comment]
Can you try this?

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}",
            "sourceMapPathOverrides": {
                "nollup://*": "${workspaceFolder}/*"
            }
        }
    ]
}
```

**Comment by zgoda** [comment]
This is it, thank you very much!

A hole in memory, I once used that override with Snowpack or Vite.
