### ISSUE TITLE
Axios

### ISSUE THREAD

**Issue by jakobrosenberg** [PepsRyuu/nollup#202]
Hi Paul. Are you aware of any issues with Axios? I had the below screenshot posted in the Routify discord. The error reportedly went away when using rollup.

![image](https://user-images.githubusercontent.com/4153004/119236237-98bbba80-bb36-11eb-9034-3e5d8fd787fc.png)
https://discord.com/channels/683709869626490889/683709871362801740/845717469603430421

This isn't a high priority by any measure. Just thought you should know. 🙂

**Comment by PepsRyuu** [comment]
Nothing comes to the top of my head as to what could be wrong. Having a look into it!

**Comment by PepsRyuu** [comment]
Seems to be an issue with ```syntheticNamedExports```. Should have a fix published either later today or tomorrow. 🙂

**Comment by PepsRyuu** [comment]
Fixed in ```0.16.5```.
