### ISSUE TITLE
0.18.0 broke some imports

### ISSUE THREAD

**Issue by charlag** [PepsRyuu/nollup#208]
Hi

Just tried upgrading to 0.18.0 for [Tutanota](https://github.com/tutao/tutanota) and the app stopped loading. The reason it the superclass is not imported (this import is not defined: https://github.com/tutao/tutanota/blob/fd7c8d8c0b010cb5af535ede5da347d812e40ef7/src/api/common/error/RestError.js#L3)

generated code looks like this:

```js
var _i0; var _defineProperty;; var _i1; var TutanotaError;

class ConnectionError extends TutanotaError {
   //...
 }
```

and TutanotaError is obviously undefined at this point. I think there's some missing condition for hoisting.

If you want to run it yourself, you can clone, change nollup to 0.18.0, `npm i`, `node make` and point any http server to build folder. I might come up with a better example later but maybe you already have an idea what might be wrong.

**Comment by PepsRyuu** [comment]
Thanks for the report. I'll have a look into this later today for you!

**Comment by PepsRyuu** [comment]
It seems like RestError isn't part of a circular chain itself, but that it happens to be a dependency of a circular chain, and therefore was hoisted even though it didn't need to be. Some dependencies of circular chains do need to be hoisted, so there is definitely a missing condition needed to make that determination. Will investigate further.

**Comment by charlag** [comment]
Sounds like it! Thanks for looking into it. No pressure, we are in no hurry to update.

**Comment by PepsRyuu** [comment]
I think I found the problem. I'm hoisting ```ClassDeclaration``` but it is not supposed to be hoisted, just the name of the class is supposed to be hoisted. The implementation is supposed to stay exactly where it is. 

```
(function () {
    new MyClass(); // fails saying cannot access MyClass before initialization
    class MyClass {}
})()
```

Working on a fix, hopefully will have something published in a bit. :)

**Comment by charlag** [comment]
Great, thanks, it works now!
