### ISSUE TITLE
Source maps do not work with @rollup/plugin-typescript

### ISSUE THREAD

**Issue by charlag** [PepsRyuu/nollup#222]
1. Clone this repo (0.18.6 = 96db07ff6674f5527620ff33b94f08271671131e)
2. `npm i`
2. go to examples/example-typescript
3. `npm start`
4. Open `http://localhost:9001` in browser
5. See that source maps do not work ("DevTools failed to load source map: Could not load content for nollup-int:///src/enum.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME")

**Comment by PepsRyuu** [comment]
It looks like the TypeScript plugin returns a source map on the ```load``` hook which is not being read at all. Will see what I can do about it!

**Comment by charlag** [comment]
@PepsRyuu awesome, thanks for checking it!

**Comment by PepsRyuu** [comment]
Fixed in ```0.18.7```

**Comment by charlag** [comment]
@PepsRyuu wow that was fast, will check on Monday, thank you again!

**Comment by PepsRyuu** [comment]
😁

If there's any issues let me know!
