### ISSUE TITLE
Support for TypeScript rollup config

### ISSUE THREAD

**Issue by cdauth** [PepsRyuu/nollup#229]
I just tried starting `nollup` in the same way that I would start `rollup`: `nollup -c rollup.config.ts --configPlugin rollup-plugin-esbuild`

It seems that the rollup config is interpreted as JavaScript, so I'm getting errors about the type annotations.

In addition, with `rollup`, I can use `-c` without the config file name, since `rollup.config.ts` is automatically detected.

**Comment by PepsRyuu** [comment]
https://github.com/PepsRyuu/nollup/pull/231 Initial version figured out. Would be great if you can confirm this addresses your use case. :) Just need to write some test cases for this and it should be good.

**Comment by PepsRyuu** [comment]
Added basic support in ```0.20.0``` and updated the TypeScript example to use this.
