### ISSUE TITLE
rollup-plugin-node-resolve version 5 is not supported (4.2.3 is).

### ISSUE THREAD

**Issue by vzaidman** [PepsRyuu/nollup#25]
the PR https://github.com/PepsRyuu/nollup/pull/24 fixed the support of version 4.2.3 but not of version 5

**Comment by PepsRyuu** [comment]
Released in 0.6.1! :)

**Comment by vzaidman** [comment]
no! this is a bug after my fix that enables 4.2.3!

**Comment by PepsRyuu** [comment]
Oh apologies, completely misread! Any further details?

**Comment by vzaidman** [comment]
it expects something to be string. didnt dig into it yet

**Comment by PepsRyuu** [comment]
```
ParseError: src\main.js
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.normalize (path.js:280:5)
    at Object.resolveId (C:\Users\paul.p.sweeney\git\github\nollup\lib\impl\PluginLifecycle.js:102:17)
```

Is that the error you're seeing? I think Rollup recently changed the function signature of ```resolveId``` so it can return an object. Saw this in ```rollup-plugin-node-resolve```: 

```
return {id: resolved, moduleSideEffects: hasModuleSideEffects(resolved)};
```

**Comment by vzaidman** [comment]
yes exactly

**Comment by PepsRyuu** [comment]
Give ```0.6.2``` a try. :)

**Comment by vzaidman** [comment]
nice! fixed!
