### ISSUE TITLE
cant-use-styled-components

### ISSUE THREAD

**Issue by vzaidman** [PepsRyuu/nollup#27]
the demo is on the branch
https://github.com/welldone-software/why-did-you-render/tree/support-styled-components

run `yarn`
run `yarn start`
open `localhost:3003`

as i understood it is fixed on `rollup-plugin-commonjs` **v9**:
https://github.com/rollup/rollup-plugin-commonjs/issues/321

so there is probably something to add to `custom-rollup-plugin-commonjs`

**Comment by PepsRyuu** [comment]
Thanks vzaidman! I'm suspecting the problem is ```module['exports']``` which I know is something I'm not checking for at all. Not entirely sure why it's even written that way in that library. I'll look into this as soon as I can. Should be an easy fix.

**Comment by PepsRyuu** [comment]
```rollup-plugin-commonjs-alternate@0.0.6``` should fix the issue. 

https://github.com/PepsRyuu/rollup-plugin-commonjs-alternate/commit/f6724863de69eab77c7d4bccf9d071dadde2e501

**Comment by vzaidman** [comment]
it works indeed. thank you!
