### ISSUE TITLE
Additional options to allow piloting by a test driver

### ISSUE THREAD

**Issue by rixo** [PepsRyuu/nollup#35]
Hi! I'm trying to implement Svelte HMR over nollup. [Initial trial](https://github.com/rixo/demo-svelte-nollup) went way over expectations. (Initial tests with 3 lines of code suggest it might be one bazillion times faster than Webpack, but it's too early to tell.)

So now I'd want to integrate the nollup setting to my [HMR test suite](https://github.com/rixo/svelte-hmr-spec), that only supports Webpack for now. (The meat of the Webpack integration is in a [sub project](https://github.com/rixo/test-hmr/blob/master/lib/test-server/test-server.js#L64).)

For that, the test harness needs some special programmatic control over the dev server that I believe is not entirely possible currently with nollup. What is needed specifically is:

1. to control a virtual input filesystem (to be able to generate test source files in memory)

2. to control / mock the file watcher

3. to know, on the server side, when bundling is complete / dev server ready (for the initial page load)

4. to know when a HMR update has completed on the client side (in order to run the assertions only when it's ready)

5. and also on the client side, after initial page load to know when the HMR client is ready (~WS connected) -- I don't really know how important this is with nollup, but it caused race conditions in the tests with Webpack

Point 4 can already be done by monitoring `[HMR]` messages in the console.

For point 5 however, there's no initial console message in nollup, which would be great to completely eliminate possibilities of race. For example, a greeting message [here](https://github.com/PepsRyuu/nollup/blob/master/lib/dev-middleware.js#L25) would do the trick nicely.

Point 3 can probably be done in a rollup plugin.

However, for the first 2 points, I see no ways to hook into nollup currently. I have experimented with passing as options the `chokidar` and `fs` objects that are used [here](https://github.com/PepsRyuu/nollup/blob/master/lib/dev-middleware.js#L57) and [here](https://github.com/PepsRyuu/nollup/blob/master/lib/dev-middleware.js#L66), and it seems to do the trick. That's quite fragile because it tightly couples the test driver to nollup's internals but, given the use case, that could be good enough for me. The rest can be done via rollup plugin, I think.

So I wanted to know what you think about this. Can you suggest better solutions, maybe? And would be you be interested in adding this kind of support to nollup? I can work on a PR if needed.

**Comment by PepsRyuu** [comment]
Hey @rixo! Thanks for reporting this issue. 🙂

It might be a silly question on my part, and I haven't tried it for this use case, but isn't it possible to use a module like ```proxyquire``` to stub ```fs```? That's pretty much what I do in my Nollup test cases: https://github.com/PepsRyuu/nollup/blob/master/test/nollup.js You wouldn't need to stub ```chokidar``` either if ```fs``` is stubbed if I'm understanding it correctly. I agree that relying on ```chokidar``` would be a bit unstable, but relying on ```fs``` should be perfectly fine. 

Do you have suggestions on point 3 and point 5?

**Comment by rixo** [comment]
Ah yes, huge! `proxyquire` Didn't know about it. Thanks! I'll need to confirm hands on, but it seems perfect for my needs.

> Do you have suggestions on point 3 and point 5?

For point 3, knowing when bundling is complete, I tried with `generateBundle` hook. Seems to work well. The goal here is to know when it's safe to load the page. But I'm kind of new to rollup so I may have missed something obvious... Any better idea?

BTW I also hook on `renderError` to catch compile errors. In fact my hope is that the cumulated simplicity of Svelte + Nollup could make it relatively easy to achieve the flawless HMR that Dan A. is pursuing with Fast Refresh. That is, catch any compile error or component (re)init error and display them in the browser instead of killing the HMR session. I failed to find how to do that with Webpack hot protocol (mainly how to propagate compile errors to the client). Not sure it's possible, it might need some adaptation. But I already have a good idea where it would fit in Nollup :)

For point 5, any greeting message in the console when HMR client is connected would do. Webpack uses `[WDS] Hot Module Replacement enabled.`. For my tests, I just reused `[HMR] Status Change ready` sent from [here](https://github.com/PepsRyuu/nollup/blob/master/lib/dev-middleware.js#L25). Maybe something more specific would be better for general purpose... "[HMR] Enabled"?

**Comment by PepsRyuu** [comment]
Hmmm. One of the techniques I use to determine if a page is ready to load is to use a module like ```wait-on```, which will periodically test to see if the bundle is actually available. You can see an example of the technique being used here: https://github.com/PepsRyuu/preact-skeleton/blob/master/package.json#L9 Do you think something like that would work here as well?

I haven't implemented ```renderError``` yet, but it shouldn't be too hard at all. More wondering how the message would be propagated to the client, and subsequently rendered by the client. The HMR client could listen to renderError, but then there would need to be some sort of ```module.hot``` API. This would probably mean diverging from the other bundlers though and implementing a new API specifically for the purpose of listening to bundling errors. Thoughts?

I can certainly add the console message to the HMR client when the verbose flag is enabled.

**Comment by rixo** [comment]
Before all, I have confirmed that the `proxyquire` solution does work for my usage. So thanks again for this pointer. It also means that I don't really need much more on your part. At least, I don't really know what I'll really need yet. I need to make some progress with my prototyping first.

The only thing left that I'm already confident would be useful is the greeting WS console message in the client. I know there's a possible race condition here and I'd prefer not to have it, even if I've not been bitten by it yet with Rollup (but it did materialize in Webpack setting).

I think `renderError` will probably be needed, but I am not sure about it yet.

> This would probably mean diverging from the other bundlers though and implementing a new API specifically for the purpose of listening to bundling errors. Thoughts?

Yes, diverging a little might be the easiest / cleanest. The change would be additive though, so it could remain compatible with the existing API. Just discussing here, but do you think that could be an option? Also, I'm wondering, where does this spec (the "hot protocol") comes from? Is that just something like imitating Webpack's original implementation, or is there something more to it?

Actually there is a way to do it over the existing protocol. That is to wrap the compile error into a successful code update, to be interpreted by the HMR runtime. Something like this:

~~~js
export default {
  __HOT_COMPILE_ERROR: { /* ... the serialized compile error */ }
}
~~~

One pain point when doing this is that the compile error then becomes invisible to the bundler, and is not logged in the terminal. That would need to be addressed, if going this route.

Also, in my case it would probably need to be made a valid Svelte component to avoid tripping other plugins targeting `*.svelte` down the line. (This proved quite challenging to do in Webpack loader.)

Anyway... Not there yet! I do believe that, in the end, error management is what will do or undo the HMR experience. But all of this is very intricate... I don't dare moving forward without the test suite to back me.

**Comment by PepsRyuu** [comment]
Are you familiar with how the race condition in Webpack works exactly? Don't want us to end up with the same problem. :) 

I try to imitate Webpack's configuration options as much as possible, just so that it's not too new or confusing and that they can easily migrate to Nollup if they so desire. For the HMR API, it's kinda a mix of Parcel and Webpack. For the status messages, it's closer to Webpack, but for ```accept``` and ```dispose``` I'm following Parcel's approach as I think it's a lot easier to work with.

Looking through the Webpack and Parcel APIs, I can't find anything that would serve this use case. Where does __HOT_COMPILE_ERROR come from? Do you think something like this would make sense?

```
let errMsg = document.createElement('div');
module.hot.compile(function (err, stats) {
    if (err) {
	errMsg.textContent = err;
	document.body.appendChild(errMsg);
    } else {
        errMsg.remove(); 
    }
});
``` 

I can probably implement something very soon once we have a good idea of what will work for you. :)

**Comment by rixo** [comment]
> Are you familiar with how the race condition in Webpack works exactly? Don't want us to end up with the same problem. :)

Maybe I wasn't very clear. The race concerns my testing code, not Webpack itself. It goes like this:

- load the page in puppeteer
- wait for page load
- trigger an HMR update (by changing the sources)
- run a set of assertions on the update
- they all fail
- ... then the WS connects and "HMR enabled" pops in the console

Waiting for the console message is a sure way to know that we're up and running without having to mess with the test page (to catch `module.hot.status` or something).

> Where does __HOT_COMPILE_ERROR come from?

I meant to catch the compile error in the plugin (that does the compilation), and generate some valid code wrapping the error instead of reporting it to the bundler. That will be sent over `hot.accept`, and it will be for the HMR runtime to see that it represents a compile error and not an actual successful update. __HOT_COMPILE_ERROR is a made up example of a marker that could be used to indicate that the updated module is actually a compile error. (By "HMR runtime", I mean the one tasked with applying the side effects of the modified code. That is, the consumer of `hot.accept` etc.)

That wouldn't make any sense to implement this at Nollup's level though. It's a workaround to pass over the existing API. Like you, I didn't find anything to do it straightforwardly in Webpack's hot API.

I like your `module.hot.compile` suggestion. It is to the point.

Having it at the module level (as opposed to global like status handler) would allow to do fancy stuff (one day...) in Svelte, like crossing out only the crashed components (since Svelte strictly enforces one component per file).

So, the lifecycle in case of compile error would be: `compile -> compile -> dispose -> accept`?

**Comment by rixo** [comment]
Ah, ah! Progress! All tests passing on both Webpack AND Nollup B-) Well, would need more tests... But that's another question!

BTW Just to be sure there is no misunderstanding... I'm not doing this in any "official" capacity. This is an experimental implementation, as a personal initiative. I do hope that my work will be useful when time comes to build official HMR support for Svelte. But for now I have no blessing from the core team.

So in the end, all I need to make Nollup compatible with my test harness is the greeting console message we've discussed above, on WS connection.

And also, it would be great to be able to make Nollup's own terminal output optional somehow. They're really distracting in tests output:

![Capture d'écran 2019-09-27 14:24:39](https://user-images.githubusercontent.com/1670419/65768939-a1c27180-e132-11e9-8ba5-225e05d874a0.png)

Being able to pass a custom logger instead of default `console.log` would be great.

Hooking on `generateBundle` from the (Svelte) HMR plugin works great.

So next would be error management. Or, say reporting. That will need either to implement `renderError` (I guess), or a hot API like the `compile` you've proposed above.

But I have to say that this is far less a pressing need with Nollup than it was with Webpack, because compile errors forces a full reload there (Why do they do that, by the way? That must be me misusing it?). Anyway, since Nollup does not apply broken updates (right?), the problem simply does not exist here. HMR session just resumes happily when errors have been fixed.

So here that would be more of a luxury-ish feature, preventing the situation we're your change doesn't get applied and you're left wondering why (before thinking to check in the term).

This is great! Really love this "not applying garbage updates" feature of Nollup ;)

**Comment by PepsRyuu** [comment]
That's excellent news! We can definitely looking into adding the console message (been a bit pre-occupied but hopefully will have time soon, PRs are also welcome).

I'm not entirely sure how beneficial a ```--silent``` option is. The only thing it would stop would be the "Listening on X" and "Compiled in 24ms" and hide error messages. If a plugin uses ```console.log```, there's very little that can be done to stop them. I think the messages need to be tidied up anyways and turned into something that looks more professional. 

If the file has been compiled successfully, it will be sent over the websocket and the UI will try to apply it. If it fails, then it fails and throws an error in the console, but it shouldn't stop any future updates from being applied. I'm guessing WebPack refreshes the page because perhaps there's some faulty stale state and presumably refreshing the page will correct that state. 

Is there a final list of features you would like to see in that case? :)

**Comment by rixo** [comment]
> Is there a final list of features you would like to see in that case? :)

If by "that case" you mean the current issue pertaining to piloting for test purposes...

The only thing I still **need** is the greeting console message.

I'm in the process of tidying up all the hacked bits I had to do to make it work for Nollup (and other improvements it inspired me!). I'll submit a PR if you haven't added it when I get there.

The only other thing I'd still **want** for this is a way to silence the "Compiled in ..." message. That's the only one that's bothered me for now. If you're not interested in it, I can live with it no problem. If you're interested, I can submit a PR too (for an option that lets override the `console.log` that is used in the middleware).

That's it on the testing front.

Regarding error reporting, that should be another issue really, but I don't have time for it right now. Like I said, it's not a priority for me with Nollup because normal behaviour is already good. For what it's worth, your `module.hot.compile` proposal seems good to me. It's probably the most straightforward to implement on my side (hence most robust). And I can already confirm that it would cover all my needs on this front, and that I would use it, eventually. So if you feel it's a good addition for Nollup, you can go for it. Otherwise, I'll open a relevant issue when time come.

Thanks again for you help, it's been precious.

**Comment by PepsRyuu** [comment]
Greeting message merged! Thanks for the contribution! :)

Will need to have a further think about ```--silent``` and ```module.hot.compile```. If you're okay with it, I think they can be opened up as separate issues each. Feels like they can be involved discussions and aren't exactly trivial to decide in terms of API design.

**Comment by rixo** [comment]
`silent` is 100% sugar for myself in tests output. Not willing to spend any time on it for now.

Totally agree that `module.hot.compile` should be thoroughly discussed before committing to something. I'll open another issue when time allows.

Turns out Webpack does have a mechanism to propagate compile errors to the client, since Webpack Dev Server manages to display them in its overlay. That's worth investigating before deciding how to do it with Nollup.

Closing this one. Thanks for your support!
