### ISSUE TITLE
Change events don't seem to fire on my OS

### ISSUE THREAD

**Issue by Mike-Dax** [PepsRyuu/nollup#4]
I'm assuming this is an issue of raw chokidar events being different across platforms. I'm running MacOS High Sierra, 10.13.6.

When I inspect the type, the string provided is 'modified' instead of 'change', and the details contains 'path' instead of 'changedPath'.

I've created a PR that uses the normalised add and change events instead if that's an acceptable fix.

**Comment by PepsRyuu** [comment]
Thanks for looking into this @Mike-Dax! I work on a Windows 10 machine with no proper access to a Mac. :( 

I'll look through this in further detail and will get back to you. :)
