### ISSUE TITLE
ParseError: child_process

### ISSUE THREAD

**Issue by derrickb** [PepsRyuu/nollup#41]
Hi there,

My bundled file ends up running in an environment that has access to node modules. In one of my modules I have:
`let spawn = require('child_process').spawn;`

When running `nollup -c` I get this error:
```
ParseError: child_process
Error: ENOENT: no such file or directory, open 'child_process'
    at parse (/node_modules/nollup/lib/index.js:93:23)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```
I've tried setting `preferBuiltins` to both true and false in the node resolve plugin options, but neither works.

Is this something that can be fixed?

**Comment by PepsRyuu** [comment]
Can you show me your ```rollup.config.js```? 

Have you tried using ```global.require``` or using an alias for ```require``` instead?

**Comment by derrickb** [comment]
Using `global.require` worked! Thank you
