### ISSUE TITLE
Require calls in some dependencies don't seem to be modified

### ISSUE THREAD

**Issue by Mike-Dax** [PepsRyuu/nollup#6]
I'm attempting to modify your example to work with React + Babel, in anticipation of being able to use HMR.

However I receive `TypeError: modules[number] is not a function` errors in the browser console upon compilation (the compile task displays the "Compiled in xxxms" message however).

When I add a `console.log(number)` in the require function nollup creates, it will iterate over the numbers 0, 1 then print `object-assign`

When inspecting sources I find dependencies of React haven't been transformed:

```
var _assign = require('object-assign');
var checkPropTypes = require('prop-types/checkPropTypes');
```

I've linked below a minimum viable repro:

https://github.com/Mike-Dax/nollup/tree/react-error

**Comment by Mike-Dax** [comment]
Ah, incredible. Thank you very much. 

Would you be open to swapping the example-project directory for an examples directory, and then I can PR a few examples for Babel+React, and Typescript+React?

**Comment by PepsRyuu** [comment]
Just a follow up on the __moduleExports, turns out it's not a bug with the CommonJS plugin, it's an intentional feature. 

https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports

So if you want to use ``` import { Component } from 'react';```, you have to add the following configuration:

```
commonjs({
    namedExports: {
        'node_modules/react/cjs/react.development.js': ['Component']
    }
})
```

**Comment by Mike-Dax** [comment]
For context, my general goals are to find / create a way to transpile TypeScript to 'ES2018' for use in Electron applications. (Electron if you're not aware is a toolkit to build desktop apps with web technologies)

The latest Electron runs Node 10.2.0, no other JS versions need to be targeted given the developer's control over their Electron version. I don't understand why the general consensus amongst the community is to utilise webpack+babel and transpile everything to ES5.

Build times on one of my applications is 45+ seconds, with hot reload times of 5+ seconds. I'd like a faster alternative. 

---

I've done some reading of React's issues, it appears as though an esmodule build in the pipeline, but there's no information on timing:

https://github.com/facebook/react/issues/11503

Yeah the requirements to get hot module reloading look irritating to deal with. I'm going to try some experiments and try to get typescript working without HMR.
