### ISSUE TITLE
HMR : some CommonJS modules are not properly started

### ISSUE THREAD

**Issue by mikbry** [PepsRyuu/nollup#65]
I got several errors using React-Color and Material-UI. I find some solutions for MUI styling, but with React-Color no ways :-(

I got a `TypeError: _common.ColorWrap is not a function` when using any React-Color pickers.

Very hard to debug as you are using eval and I get an infinite loop with 'React Dev Tools'...

The error is line 208 in Twitter.js component of React-Color:
```javascript
exports.default = (0, _common.ColorWrap)(Twitter);
```
_common.ColorWrap is undefined.

I use my rollup-react-app template for the test. And I only add a React-Color Twitter component to the App to reproduce the bug.

<img width="1350" alt="Screenshot 2020-02-12 at 15 02 32" src="https://user-images.githubusercontent.com/395718/74343381-445e5280-4dab-11ea-8fc0-aeb476a16357.png">

**Comment by PepsRyuu** [comment]
Haven't looked into it much yet, but I suspect it's this:

```
Object.defineProperty(exports, 'ColorWrap', {
    enumerable: true,
    get: function get() {
         return _interopRequireDefault(_ColorWrap).default;
    }
});
```

The CommonJS plugin isn't detecting this. Should be possible to add support for.

**Comment by PepsRyuu** [comment]
Update ```rollup-plugin-commonjs-alternate``` to ```0.4.0```. Added support for ```Object.defineProperty(exports, <export-name>)```.

**Comment by mikbry** [comment]
Thanks @PepsRyuu ! This new version fixed the bug. I updated `rollup-react-app`
