### ISSUE TITLE
TypeError: Renderer.injectIntoDevTools is not a function

### ISSUE THREAD

**Issue by mikbry** [PepsRyuu/nollup#67]
I test [react-three-fiber](https://github.com/react-spring/react-three-fiber/) with my `rollup-react-app` But the first example in README.md is crashing:
![Screenshot 2020-02-15 at 12 20 00](https://user-images.githubusercontent.com/395718/74587281-efac1900-4ff0-11ea-995b-5a7a203fd4df.png)

![Screenshot 2020-02-15 at 12 19 43](https://user-images.githubusercontent.com/395718/74587311-3e59b300-4ff1-11ea-89e2-6941537034f1.png)

After some investigation to check if i need some other modules, I think it is a bug in Nollup not importing correctly `react-reconcilier`.

**Comment by PepsRyuu** [comment]
Try ```rollup-plugin-commonjs-alternate@0.5.0```. There was a breaking bug in the previous version that the tests didn't capture. Seems to bypass that error now.

**Comment by mikbry** [comment]
Thanks, I upgraded to 0.5.0, but now I get another error:
![Screenshot 2020-02-16 at 14 16 19](https://user-images.githubusercontent.com/395718/74605284-07ee6780-50c7-11ea-9d30-eacd1d6f72e2.png)

**Comment by PepsRyuu** [comment]
Can you provide a sample of the code that triggers the error? Is there a particular import?

**Comment by mikbry** [comment]
The code is very simple, based on `react-three-fiber` example I modified my boilerplate App.jsx with:
```javascript
// From react-three-fiber
import React, { useRef, useState } from 'react';
import { Canvas, useFrame } from 'react-three-fiber';

function Box() {
  // This reference will give us direct access to the mesh
  const mesh = useRef();

  // Set up state for the hovered and active state
  const [hovered, setHover] = useState(false);
  const [active, setActive] = useState(false);

  // Rotate mesh every frame, this is outside of React without overhead
  useFrame(() => {
    mesh.current.rotation.x = mesh.current.rotation.y += 0.01;
  });

  return (
    <mesh
      ref={mesh}
      scale={active ? [1.5, 1.5, 1.5] : [1, 1, 1]}
      onClick={() => setActive(!active)}
      onPointerOver={() => setHover(true)}
      onPointerOut={() => setHover(false)}
    >
      <boxBufferGeometry attach="geometry" args={[1, 1, 1]} />
      <meshStandardMaterial attach="material" color={hovered ? 'hotpink' : 'orange'} />
    </mesh>
  );
}

function App() {
  return (
    <Canvas>
      <ambientLight />
      <pointLight position={[10, 10, 10]} />
      <Box position={[-1.2, 0, 0]} />
      <Box position={[1.2, 0, 0]} />
    </Canvas>
  );
}

export default App;
```
And added module three and react-three-fiber. Same code works using `create-react-app`.

**Comment by PepsRyuu** [comment]
Try ```nollup@0.10.6``` with ```rollup-plugin-commonjs-alternate@0.5.1```. There's a few packages (like debounce and TinyEmitter) that are adding export properties to functions as opposed to objects, which the synthetic exports feature in Nollup didn't see.

**Comment by mikbry** [comment]
Yep it works now !
