### ISSUE TITLE
A nollup API

### ISSUE THREAD

**Issue by antony** [PepsRyuu/nollup#83]
Hi.

Without really knowing how possible this is, based on how nollup works - is it possible / are there any plans for nollup to expose an API matching Rollup's API?

The reason being is that we're toying with the possiblity of using `nollup` for development mode in Sapper / Svelte apps to speed up the developer feedback loop, but currently I've not been able to get too far due to the lack of a compatible API.

Thread is here https://github.com/sveltejs/sapper/issues/1207#issuecomment-630067410

**Comment by PepsRyuu** [comment]
Hey Antony!

There is an API already available that's aligned to Rollup (there may be some slight discrepancies though given the different objectives): https://github.com/PepsRyuu/nollup/blob/master/API.md

Is there something in particular that's missing or not working as expected?

**Comment by antony** [comment]
Hey @PepsRyuu it might just be me! I think I was getting confused about where the generate method originated from :)

I'm getting a bit further now. Thanks for pointing me at the API docs, not sure how I missed those the first time around. I'm going to examine @rixo 's fork to see how his integration works too.

**Comment by PepsRyuu** [comment]
Let me know if there's anything I can do to assist with this! It seems very interesting! :)
