### ISSUE TITLE
Support `output.format: 'es'`

### ISSUE THREAD

**Issue by rixo** [PepsRyuu/nollup#91]
Rollup accepts all of `es`, `esm` and `module` as valid values for ESM `output.format`, with `es` apparently being the preferred form used in the docs. See [output.format](https://rollupjs.org/guide/en/#outputformat) in the docs.

But Nollup only accepts `esm`, and so it tends to be in disagreement with configs of recent projects.

I suppose it would also make sense to implement support for `commonjs` alias for `cjs`.

**Comment by PepsRyuu** [comment]
Pushed to the ```refactor``` branch. All aliases included. There's a weird thing I noticed in Rollup, is that if you use ```[format]``` for your filenames, it outputs ```es``` as ```esm```. So that's also been emulated.

**Comment by rixo** [comment]
Great! Thanks a lot. This was the most annoying to repatch ^^ Working everywhere for me (well... meaning I've only tested `es`, but I trust you on this one).

I leave for you to close issues when officially released, right?

**Comment by PepsRyuu** [comment]
Yep! I'll wait until everything is merged and released. :)

**Comment by PepsRyuu** [comment]
Released in ```0.12.0```
