### ISSUE TITLE
Allow `options` and `outputOptions` hooks to mutate / change the passed options object

### ISSUE THREAD

**Issue by rixo** [PepsRyuu/nollup#92]
In Rollup, plugins are allowed to change the options that are passed to the `options` and `outputOptions` hooks.

> Replaces or manipulates the options object passed to rollup.rollup. Returning null does not replace anything. [docs](https://rollupjs.org/guide/en/#options)

In Nollup, it seems that the options object is cached too early for any further modification to be taken into account.

One of my plugins hijacks the user's config, notably with the `outputOptions` hook. I had to apply [this dirty patch](https://github.com/rixo/nollup/blob/next/lib/impl/NollupContext.js#L137) to make it work.

**Comment by PepsRyuu** [comment]
Pushed fixes to the ```refactor``` branch for both ```outputOptions``` and not crashing on ```plugins``` array disappearing.

**Comment by rixo** [comment]
All good to me. Works with return or mutate, both `options` and `outputOptions`. I can also confirm it's working in the real world project with the plugin using this hook.

**Comment by PepsRyuu** [comment]
Released in ```0.12.0```
